# Generated by Django 3.2.7 on 2021-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_roll', models.IntegerField()),
                ('stu_name', models.CharField(max_length=40)),
                ('stu_dep', models.CharField(max_length=40)),
                ('stu_email', models.EmailField(max_length=20)),
                ('stu_pass', models.CharField(max_length=15)),
            ],
        ),
    ]
